version: '3.9'
configs:
  app_config:
    file: ./config.docker.edn
services:
  app:
    build: .
    ports:
      - 8079:3000
    volumes:
      - ./data-vol:/data
    configs:
      - source: app_config
        target: /app/config.edn
  nginx:
    image: nginx:stable
    ports:
      - 8000:80
    volumes:
      - ./data-vol:/data
      - ./nginx/conf.d:/etc/nginx/conf.d



