version: '3.9'
configs:
  app_config:
    file: ./config.docker.edn
services:
  app:
    image: resources-cleanup-app
    build: .
    ports:
      - 8079:3000
    volumes:
      - /home/nas/proiecte/resources-cleanup-docker-vol:/app/data
    configs:
      - source: app_config
        target: /app/config.edn
  nginx:
    image: nginx
    build: .
    ports:
      - 8000:80
    volumes:
      - /home/nas/proiecte/nginx-volume:/usr/share/nginx/html/



